### ISSUE TITLE
Ember Inspector modifies Changeset with Ember Data Models

### ISSUE THREAD

**Issue by basz** [poteto/ember-changeset#485]
An issue of the inspector (probably), but please be aware of this https://github.com/emberjs/ember-inspector/issues/1225

**Comment by snewcomer** [comment]
Tldr we have a proxy set so you can return out any level of the tree and add to the changes array.  This recursive object proxy is probably our final design of this library.  It solves if not all of our nested getter/setter problems.

However I'm at a loss of how to prevent the issue you detailed.  (toArray has similar behaviour).  One option is we don't allow set on a nested node of your object tree, but that presents some downsides as well.

https://github.com/validated-changeset/validated-changeset/blob/master/src/utils/object-tree-node.ts

**Comment by basz** [comment]
I'm sure ember-inspector has a valid reason to set those properties on ember-data models. I'm just sure the magic ember-changeset does is needed and fine in general. I just never realized simply opening the inspector can actually change the behavior of the application you are inspecting and is something one should be aware of.

**Comment by snewcomer** [comment]
We may have to disable this (and only allow changeset.set('belongsToModel.name')) for ED objects

**Comment by snewcomer** [comment]
I think we may have two options - 

1. Add a method `registerKeys` that accepts a list of keys to check (optionally) when `isDirty` is asked for.
2. Update the `Changeset` constructor to accept a list of changeset keys.  We could then check dirty status against a list of pre-approved keys.  Moreover, when we come across some other system mutating the changeset object, we can set the rogue value on the changeset object instead of the underlying `CHANGES`.  We basically would be making the Changeset more Elixir like (Structs) while making it less prone to the outside world. 

Have any thoughts @basz?

https://github.com/validated-changeset/validated-changeset/blob/e985bba31d8cc0fae229e3118d8041c472e6d62f/src/utils/object-tree-node.ts#L66

**Comment by basz** [comment]
A fourth argument on the constructor might be the simplest... array containing keyPaths..? acting as a filter on dirty... 

I image it would also restrict the validate() call to those present in that argument. As if you call validate(keystovalidatearray).

However I am more surprised that the inspector can make changes directly to the changeset after creating that changeset from a ember data model? I assume some sort of promise on the models is adding those changes. But you would think that would affect the model, not the changeset....

**Comment by snewcomer** [comment]
We trap both #get and #set so as to provide retrieving and setting values at any level in the object tree.  See link above where a node in your object tree can set a value on the changes.

**Comment by snewcomer** [comment]
Fixed in 3.5!

**Comment by billybonks** [comment]
I am facing the same issue,

Ember inspector v4.3.4 
Ember changeset v3.10.5

**Comment by mikeburg** [comment]
This is still broken. _oldWillDestroy & willDestroy are being set within the changeset object.

Ember Inspector 4.3.4
Ember 3.24.1
Ember changeset 3.13.1

**Comment by patrickberkeley** [comment]
Running into the same issue with these versions:

Ember Inspector | 4.3.5
Ember | 3.26.1
Ember Changeset | 3.7.1
